### ISSUE TITLE
Add typescript and chai to dependencies

### ISSUE THREAD

**Issue by aikoven** [adamcarr/typescript-definition-tester#1]
When I do 

```
$ npm install typescript-definition-tester
```

modules that are listed in `devDependencies` don't get installed and importing `typescript-definition-tester` fails because it can't find `typescript` and `chai`.

**Comment by adamcarr** [comment]
Thanks for reaching out. I'll address this in the next day or so.

**Comment by adamcarr** [comment]
These changes have been made and I pushed a new version to npmjs.org

**Comment by aikoven** [comment]
Great, thanks!
